@startuml

actor "User" as u
participant Partnermanagement as pm
participant Vertragsmanagement as vm
participant "Kafka Connect" as kc
database "partner-topic" as pt
database "contract-topic" as ct
database "overview-topic" as ot
participant "ic-overview" as io

u -> pm: update
kc -> pm: watch
kc -> pt: produce event
pt -> io: consume event
activate io
u -> vm: updates
kc -> pm: watch
kc -> ct: produce event
ct -> io: consume event
io -> io: join partner & contract events
io -> ot: produce event
deactivate io

@enduml